### ISSUE TITLE
resource argocd_application crashes on creation

### ISSUE THREAD

**Issue by beyondbill** [oboukili/terraform-provider-argocd#152]
**Terraform code:**

```terraform
resource "argocd_application" "donkey" {
  wait = true

  metadata {
    name      = "donkey-6b80c"
    namespace = "argocd"
  }

  spec {
    source {
      repo_url = "https://github.com/fivetran/argocd.git"
      path     = "argo_configs/donkey"

      helm {
        value_files = ["../../clusters/donkey/prod/azure-donkey-uk-south-knowing-yak/donkey_values.yaml"]
      }
    }

    destination {
      server    = "https://kubernetes.default.svc"
      namespace = "argocd"
    }

    sync_policy {
      automated = {}
    }
  }
}
```

**Plan:**

```
  # argocd_application.donkey will be created
+ resource "argocd_application" "donkey" {
      + cascade = true
      + id      = (known after apply)
      + wait    = true

      + metadata {
          + generation       = (known after apply)
          + name             = "donkey-6b80c"
          + namespace        = "argocd"
          + resource_version = (known after apply)
          + uid              = (known after apply)
        }

      + spec {
          + project = "default"

          + destination {
              + namespace = "argocd"
              + server    = "https://kubernetes.default.svc"
            }

          + source {
              + path     = "argo_configs/donkey"
              + repo_url = "https://github.com/fivetran/argocd.git"

              + helm {
                  + value_files = [
                      + "../../clusters/donkey/prod/azure-donkey-uk-south-knowing-yak/donkey_values.yaml",
                    ]
                }
            }

          + sync_policy {
            }
        }
    }
```

**Logs:**

```
2022/03/18 21:31:11 [WARN] Provider "registry.terraform.io/oboukili/argocd" produced an invalid plan for argocd_application.donkey, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .cascade: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .spec[0].project: planned value cty.StringVal("default") does not match config value cty.NullVal(cty.String)
      - .spec[0].sync_policy[0].automated: planned value cty.NullVal(cty.Map(cty.Bool)) does not match config value cty.MapValEmpty(cty.Bool)
2022/03/18 21:31:11 [TRACE] EvalCheckPlannedChange: Verifying that actual change (action Create) matches planned change (action Create)
2022/03/18 21:31:11 [TRACE] EvalReadState: reading state for argocd_application.donkey
2022/03/18 21:31:11 [TRACE] EvalReadState: no state present for argocd_application.donkey
2022/03/18 21:31:11 [DEBUG] EvalApply: ProviderMeta config value set
2022/03/18 21:31:11 [DEBUG] argocd_application.donkey: applying the planned Create change
2022/03/18 21:31:11 [TRACE] GRPCProvider: ApplyResourceChange
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: panic: interface conversion: interface {} is nil, not map[string]interface {}
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6:
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: goroutine 24 [running]:
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: github.com/oboukili/terraform-provider-argocd/argocd.expandApplicationSyncPolicy(0xc0008b1340, 0x1, 0x1, 0xb, 0xc0008c4888, 0x1, 0x0)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	github.com/oboukili/terraform-provider-argocd/argocd/structure_application.go:264 +0xc45
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: github.com/oboukili/terraform-provider-argocd/argocd.expandApplicationSpec(0xc000896c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	github.com/oboukili/terraform-provider-argocd/argocd/structure_application.go:45 +0x2ea
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: github.com/oboukili/terraform-provider-argocd/argocd.expandApplication(0xc000896c80, 0xc000194a24, 0xc, 0x0, 0x0, 0xc000194a3a, 0x6, 0x0, 0x0, 0x0, ...)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	github.com/oboukili/terraform-provider-argocd/argocd/structure_application.go:21 +0x106
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: github.com/oboukili/terraform-provider-argocd/argocd.resourceArgoCDApplicationCreate(0x2c4f238, 0xc0008aa3c0, 0xc000896c80, 0x25e6c00, 0xc00007e840, 0xc0008b1040, 0x6fcb8a, 0xc000b162c0)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	github.com/oboukili/terraform-provider-argocd/argocd/resource_argocd_application.go:53 +0xc5
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001e9b20, 0x2c4f1c8, 0xc0007690c0, 0xc000896c80, 0x25e6c00, 0xc00007e840, 0x0, 0x0, 0x0)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:330 +0x17f
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001e9b20, 0x2c4f1c8, 0xc0007690c0, 0xc000578af0, 0xc000b162c0, 0x25e6c00, 0xc00007e840, 0x0, 0x0, 0x0, ...)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:456 +0x67b
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000122018, 0x2c4f1c8, 0xc0007690c0, 0xc0006db220, 0xc0007690c0, 0x270c260, 0xc000785d00)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/grpc_provider.go:955 +0x8ef
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000b16840, 0x2c4f270, 0xc0007690c0, 0xc0005788c0, 0xc000b16840, 0xc000785d40, 0xc0000e5ba0)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x270c260, 0xc000b16840, 0x2c4f270, 0xc000785d40, 0xc000327f20, 0x0, 0x2c4f270, 0xc000785d40, 0xc000b58b00, 0x569)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003b5180, 0x2c69278, 0xc0005fc480, 0xc000790480, 0xc000624b70, 0x3e2e6e0, 0x0, 0x0, 0x0)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	google.golang.org/grpc@v1.40.0/server.go:1297 +0x52b
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: google.golang.org/grpc.(*Server).handleStream(0xc0003b5180, 0x2c69278, 0xc0005fc480, 0xc000790480, 0x0)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	google.golang.org/grpc@v1.40.0/server.go:1626 +0xd0c
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00005a1e0, 0xc0003b5180, 0x2c69278, 0xc0005fc480, 0xc000790480)
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	google.golang.org/grpc@v1.40.0/server.go:941 +0xab
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-03-18T21:31:11.657Z [DEBUG] plugin.terraform-provider-argocd_v2.2.6: 	google.golang.org/grpc@v1.40.0/server.go:939 +0x1fd
2022-03-18T21:31:11.659Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-03-18T21:31:11.659Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/oboukili/argocd/2.2.6/linux_amd64/terraform-provider-argocd_v2.2.6 pid=16945 error="exit status 2"
2022/03/18 21:31:11 [DEBUG] argocd_application.donkey: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
```

**Additional information:**

Terraform version is **v0.14.7**. The issue is confirmed on both terraform-provider-argocd_**v2.2.6** and **v2.1.0**

Within the same root module, a `argocd_cluster` (see below) can be successfully created from the same `argocd` provider definition. So the issue is unlikely wrong provider configuration.

```terraform
resource "argocd_cluster" "cluster" {
  server = var.cluster.url
  name   = var.cluster.name

  config {
    bearer_token = data.kubernetes_secret.argocd_manager.data.token

    tls_client_config {
      ca_data = data.kubernetes_secret.argocd_manager.data["ca.crt"]
    }
  }
}
```

There are other `argocd_application`s in the same root module and all of them experience the same issue during creation.

**Comment by oboukili** [comment]
Should be solved by #156
