### ISSUE TITLE
Unable to Use kubernetes provider for auth in resource argocd_cluster 

### ISSUE THREAD

**Issue by kgiri241** [oboukili/terraform-provider-argocd#206]
Hello Team,

We would like to use the argocd_cluster resource but authenticate to the target cluster using the kubernetes provider.
Our code block looks like below

terraform {
  required_providers {
    argocd = {
      source  = "oboukili/argocd"
      version = "3.2.1"
    }
  }
}

provider "argocd" {
  server_addr = var.argocd_server_address
  auth_token  = var.argocd_auth_token
}

provider "kubernetes" {
  host                   = var.kubernetes_server_address
  cluster_ca_certificate = base64decode(var.kubernetes_ca_data)
  token                  = var.kubernetes_sa_bearer_token
}

resource "argocd_cluster" "kubernetes_cluster" {
  server = var.kubernetes_server_address
  name   = var.kubernetes_cluster_name
  config {
    tls_client_config {
    }
  }
}

We keep getting the error as the config block is empty but the target cluster is being authenticated in the provider section. Could you please let us know if this is possible. we would like to avoid the auth to target cluster in the resource block.

We are getting the below message while trying the above 

############
╷
│ Error: Plugin did not respond
│ 
│   with argocd_cluster.kubernetes_cluster,
│   on main.tf line 2, in resource "argocd_cluster" "kubernetes_cluster":
│    2: resource "argocd_cluster" "kubernetes_cluster" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-argocd_v3.2.1 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 52 [running]:
github.com/oboukili/terraform-provider-argocd/argocd.expandClusterConfig(0x106505940, 0x1400056b4a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/oboukili/terraform-provider-argocd/argocd/structure_cluster.go:75 +0xd0c
github.com/oboukili/terraform-provider-argocd/argocd.expandCluster(0x140001e6680, 0x0, 0x0, 0x0)
        github.com/oboukili/terraform-provider-argocd/argocd/structure_cluster.go:36 +0x2c8
github.com/oboukili/terraform-provider-argocd/argocd.resourceArgoCDClusterCreate(0x1068fbc98, 0x1400032d140, 0x140001e6680, 0x1066286e0, 0x140002530e0, 0x14000612710, 0x140004c4400, 0x104822300)
        github.com/oboukili/terraform-provider-argocd/argocd/resource_argocd_cluster.go:38 +0x160
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140001f9500, 0x1068fbc28, 0x140006a0bc0, 0x140001e6680, 0x1066286e0, 0x140002530e0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:330 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140001f9500, 0x1068fbc28, 0x140006a0bc0, 0x14000bda230, 0x140004c4400, 0x1066286e0, 0x140002530e0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:456 +0x4ec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000ca80, 0x1068fbc28, 0x140006a0bc0, 0x14000bd02d0, 0x140006a0bc0, 0x10674dcc0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/grpc_provider.go:955 +0x6f8
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0x14000c67020, 0x1068fbcd0, 0x140006a0bc0, 0x14000bda000, 0x14000c67020, 0x104ad94f0, 0x1066d24c0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0x94
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10674dcc0, 0x14000c67020, 0x1068fbcd0, 0x14000bce1b0, 0x1400032c9c0, 0x0, 0x1068fbcd0, 0x14000bce1b0, 0x14000bd8500, 0x25a)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1c8
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002d8e00, 0x106916338, 0x140006cb800, 0x14000bd6000, 0x140009c4e40, 0x107aa31a0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1297 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x140002d8e00, 0x106916338, 0x140006cb800, 0x14000bd6000, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1626 +0xa50
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400069a1c0, 0x140002d8e00, 0x106916338, 0x140006cb800, 0x14000bd6000)
        google.golang.org/grpc@v1.40.0/server.go:941 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.40.0/server.go:939 +0x1f8

Error: The terraform-provider-argocd_v3.2.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by onematchfox** [comment]
Configuration of the [ArgoCD cluster](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters) resource is a separate concern from configuring the [Kubernetes Terraform provider](https://registry.terraform.io/providers/hashicorp/kubernetes). Please refer to the [docs](https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/cluster) for the `argocd_cluster` resource and ensure you populate the `config` correctly.
