### ISSUE TITLE
Error: Plugin did not respond

### ISSUE THREAD

**Issue by trongnd-vgs** [oboukili/terraform-provider-argocd#362]
### Terraform Version, ArgoCD Provider Version and ArgoCD Version

```
Terraform version:
ArgoCD provider version:
ArgoCD version:
```

## Terraform configuration
```hcl
# Enter your configuration here.
```

## Question
Error: Plugin did not respond

The plugin encountered an error, and failed to respond to the
plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.

**Comment by WachTy** [comment]
Any update or solution? Having the same issue. Provider version upgrade did not help. Thanks in advance!

**Comment by WachTy** [comment]
My **versions**:

source = "hashicorp/azurerm"
- version = "3.47.0"
   
source = "oboukili/argocd"
- version = "6.0.3"

source = "hashicorp/kubernetes"
- version = "2.18.1"

As mentioned same error with newest versions.


**Error**:
`C:\Users>terraform plan
module.test.data.azurerm_kubernetes_cluster.testappg3_aks: Reading...
module.test.data.azurerm_key_vault.key_vault: Reading...
data.azurerm_key_vault.key_vault: Reading...
data.azurerm_kubernetes_cluster.testappg3_aks: Reading...
azurerm_private_dns_a_record.testappg3: Refreshing state... [id=/subscriptions/501efccb-7555-4c2a-9add-52c6e853a632/resourceGroups/group-dns/providers/Microsoft.Network/privateDnsZones/testappg3-dev.azure.cloud.xy/A/testappg3]
module.test.data.azurerm_key_vault.key_vault: Read complete after 1s [id=/subscriptions/501efccb-7555-4c2a-9add-52c6e853a632/resourceGroups/testappg3devgreen-kaas/providers/Microsoft.KeyVault/vaults/testappg3devgreenmezhv]
module.test.data.azurerm_key_vault_secret.kafka-schema-registry-secret: Reading...
module.test.data.azurerm_key_vault_secret.kafka-schema-registry-key: Reading...   
module.test.data.azurerm_key_vault_secret.argocd-token: Reading...
module.test.data.azurerm_key_vault_secret.plantcon-sasl-password: Reading...      
module.test.data.azurerm_key_vault_secret.testappg3-cert: Reading...
module.test.data.azurerm_key_vault_secret.plantcon-sasl-username: Reading...      
data.azurerm_key_vault.key_vault: Read complete after 1s [id=/subscriptions/501efccb-7555-4c2a-9add-52c6e853a632/resourceGroups/testappg3devgreen-kaas/providers/Microsoft.KeyVault/vaults/testappg3devgreenmezhv]
module.test.data.azurerm_key_vault_secret.kafka-sasl-password: Reading...
module.test.data.azurerm_key_vault_secret.kafka-sasl-username: Reading...
data.azurerm_kubernetes_cluster.testappg3_aks: Read complete after 2s [id=/subscriptions/501efccb-7555-4c2a-9add-52c6e853a632/resourceGroups/testappg3devgreen-kaas/providers/Microsoft.ContainerService/managedClusters/testappg3devgreen-cluster]
module.test.data.azurerm_key_vault_secret.testappg3-key: Reading...
module.test.data.azurerm_key_vault_secret.plantcon-sasl-username: Read complete after 1s [id=https://testappg3devgreenmezhv.vault.azure.net/secrets/plantcon-sasl-username/68051a51b910450bb0d568cd99bf5479]
data.azurerm_key_vault_secret.argocd-token: Reading...
module.test.data.azurerm_key_vault_secret.kafka-schema-registry-secret: Read complete after 1s [id=https://testappg3devgreenmezhv.vault.azure.net/secrets/kafka-schema-registry-secret/31eb6945730b46cea746f8391e3648cd]
module.test.data.azurerm_key_vault_secret.kafka-schema-registry-key: Read complete after 1s [id=https://testappg3devgreenmezhv.vault.azure.net/secrets/kafka-schema-registry-key/49439e5252ce47e1a8a6d4f845e995b3]      
module.test.data.azurerm_key_vault_secret.argocd-token: Read complete after 1s [id=https://testappg3devgreenmezhv.vault.azure.net/secrets/argocd-token/3dab5fb9c721436c95390efefe6ed842]
module.test.data.azurerm_key_vault_secret.kafka-sasl-username: Read complete after 1s [id=https://testappg3devgreenmezhv.vault.azure.net/secrets/kafka-sasl-username/e4039f9a06ed42c08c0440da01dddd12]
module.test.data.azurerm_key_vault_secret.kafka-sasl-password: Read complete after 1s [id=https://testappg3devgreenmezhv.vault.azure.net/secrets/kafka-sasl-password/5b81fece469f4255a0f536a2eb7a541c]
module.test.data.azurerm_key_vault_secret.testappg3-cert: Read complete after 1s [id=https://testappg3devgreenmezhv.vault.azure.net/secrets/testappg3-cert/f11061a3b60e47ae8704f58048feece6]
module.test.data.azurerm_key_vault_secret.plantcon-sasl-password: Read complete after 1s [id=https://testappg3devgreenmezhv.vault.azure.net/secrets/plantcon-sasl-password/e061e80b903c4e63b48262d2c0cdd090]
module.test.data.azurerm_key_vault_secret.testappg3-key: Read complete after 0s [id=https://testappg3devgreenmezhv.vault.azure.net/secrets/testappg3-key/d537eecd4b054b20be3b83028c5f708e]
kubernetes_namespace.testappg3: Refreshing state... [id=testappg3]
data.azurerm_key_vault_secret.argocd-token: Read complete after 2s [id=https://testappg3devgreenmezhv.vault.azure.net/secrets/argocd-token/3dab5fb9c721436c95390efefe6ed842]
module.test.data.azurerm_kubernetes_cluster.testappg3_aks: Read complete after 6s [id=/subscriptions/501efccb-7555-4c2a-9add-52c6e853a632/resourceGroups/testappg3devgreen-kaas/providers/Microsoft.ContainerService/managedClusters/testappg3devgreen-cluster]
module.test.kubernetes_namespace.testappg3: Refreshing state... [id=w05t41201001]
module.test.kubernetes_secret.testappg3-cert: Refreshing state... [id=w05t41201001/testappg3-cert]
module.test.argocd_application.testappg3: Refreshing state... [id=w05t41201001:argocd]

Planning failed. Terraform encountered an error while generating this plan.

Error: **Plugin did not respond**
The plugin encountered an error, and failed to respond to the plugin6.(***GRPCProvider**).**ReadResource** call. The plugin logs may contain more details.

Stack trace from the terraform-provider-argocd_v6.0.3.exe plugin:

panic: set item just set doesn't exist

goroutine 196 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setSet(0xc00010bb00, {0xc001106600, 0x3, 0x3}, {0x2a60140, 0xc00010bce0}, 0xc0005fde00)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:327 +0x959
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00010bb00, {0xc001106600, 0x3, 0x3}, {0x2a60140, 0xc00010bce0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:107 +0x14c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc0009e4560?, {0xc0009e4560?, 0x2, 0x2}, {0x2bf52c0, 0xc001009770})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:222 +0x312
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00010bb00, {0xc0009e4560, 0x2, 0x2}, {0x2bf52c0, 0xc001009770})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:109 +0x11c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:122
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc00010bb00, {0xc00061bbb0?, 0x1, 0x1}, {0x2a600c0, 0xc00010bd70})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:142 +0x52a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00010bb00, {0xc00061bbb0, 0x1, 0x1}, {0x2a600c0, 0xc00010bd70})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:103 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0xc00010bb00, {0xc00061bbb0, 0x1, 0x1}, {0x2a600c0, 0xc00010bd70})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:89 +0x3f9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc0014da980, {0x30d2358, 0x4}, {0x2a600c0, 0xc00010bd70})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource_data.go:227 +0x210
github.com/oboukili/terraform-provider-argocd/argocd.flattenApplication(0xc001089000, 0x372d740?)
        github.com/oboukili/terraform-provider-argocd/argocd/structure_application.go:536 +0x288
github.com/oboukili/terraform-provider-argocd/argocd.resourceArgoCDApplicationRead({0x372d740, 0xc0014c8a20}, 0xc0014da980, {0x2ebc380?, 0xc000a36c80})
        github.com/oboukili/terraform-provider-argocd/argocd/resource_argocd_application.go:229 +0x2a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0009cec40, {0x372d778, 0xc001490ea0}, 0xd?, {0x2ebc380, 0xc000a36c80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0009cec40, {0x372d778, 0xc001490ea0}, 0xc001600d00, {0x2ebc380, 0xc000a36c80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000295848, {0x372d778?, 0xc001490d20?}, 0xc0014c03c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x3741430?, 0xc000295848?}}, {0x372d778?, 0xc001490d20?}, 0xc0014c0240?)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server/tf5to6server.go:105 +0x242
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadResource({0xc000e3e7b0, 0xc000e3e810, {0xc00050d2a0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc000e46460, {0x372d778?, 0xc001490030?}, 0xc0014c80c0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:746 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x2f740a0?, 0xc000e46460}, {0x372d778, 0xc001490030}, 0xc000c5c000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:383 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008321e0, {0x373b920, 0xc0011816c0}, 0xc0016c9e60, 0xc000c7d710, 0x50d9470, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0008321e0, {0x373b920, 0xc0011816c0}, 0xc0016c9e60, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

**Error: The terraform-provider-argocd_v6.0.3.exe plugin crashed!**

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

**Comment by onematchfox** [comment]
@WachTy that looks like a different error to what was originally reported here. Can you please open a new issue? Please also include the ArgoCD Terraform resources in the bug description. Finally, can you also check that your issue is not perhaps related to #277 (the fix for which has not been released yet).
