### ISSUE TITLE
Feature Request: Add `argocd_cluster` resource type.

### ISSUE THREAD

**Issue by rojopolis** [oboukili/terraform-provider-argocd#37]
I'd like to be able to add kubernetes clusters to my ArgoCD deployments with Terraform.  

```hcl
resource "argocd_cluster" "my_cluster"{
  config = {
    aws_auth_config = {
      cluster_name = "my-cluster"
      role_arn = "arn:..."
    }
    ...
```

I can implement this myself if it's a feature that's interesting to other people.

**Comment by rojopolis** [comment]
Hi @oboukili are you proposing to convert the existing resources to take advantage of terraform-plugin-go as part of this implementation?  I haven't used it, but I'd be happy to use it for the cluster resource specifically, or if you have something in mind and would rather do it yourself I'm happy to take a backseat.  Golang is not my comfort zone, but I have contributed to a few providers and related projects in the past.  I anticipate I'll have time in the next few weeks to implement.

**Comment by oboukili** [comment]
Yes we could start with this new resource to experiment with the new library. I personally will not have much time to bring this to completion by myself, so feel free to open a PR 👍

**Comment by oboukili** [comment]
Hello, this is going to be tackled quite soon after all, I'll keep you posted!

**Comment by onematchfox** [comment]
Hey @oboukili, Recently started playing around with this provider and would also have a need for this resource. So I wanted to check in to see if you've made any progress and to also extend an offer to help if you need any assistance? Don't see any branches on the repo but if you have WIP somewhere and want to collaborate then let me know?

**Comment by oboukili** [comment]
Hi @onematchfox , sorry about the lack of news, I should get started on that next week. Once that feature is available, I would gladly appreciate any help on how to add major cloud Kubernetes (EKS, GKE, AKS) authentication modules. I will focus on a generic one to begin with.
Stay tuned,

**Comment by onematchfox** [comment]
Great stuff. Thanks for the update. I'm working on EKS so happy to help out there.

**Comment by oboukili** [comment]
ArgoCD actually exposes a specific EKS authentication module, so that should be straightforward. I'll see what I can do after this feature request to contribute a GKE one on ArgoCD if I can !

**Comment by oboukili** [comment]
@rojopolis @onematchfox I am almost done with the implementation, only missing some tests regarding tls client configuration and docs. Would you be willing to build the provider from the `37-resource-argocd-cluster` branch and test out the things I cannot test on my end? Namely the AWS authentication configuration.

 The resource configuration should look like this:
```hcl
resource "argocd_cluster" "eks" {
  server     = "https://ip:port"
  name       = "optional"
  namespaces = ["still", "optional"]

  config {
    aws_auth_config {
      cluster_name = "myekscluster"
      role_arn     = "arn:aws:iam::<123456789012>:role/<role-name>" 
    }

    // Not sure if this block is needed at all with AWS auth config?
    //  tls_client_config {
    //    ca_data     = "string"
    //    cert_data   = "string"
    //    key_data    = "string"
    //    server_name = "string"
    //    insecure    = true
    //  }
  }
}
```

Once at least one of you validates is working fine I will release this, thanks for your help 🙏

**Comment by onematchfox** [comment]
Hi @oboukili,

I'm afraid this isn't working for me. Trace logs follow - let me know if you need anything else:

``` 
argocd_cluster.cluster: Creating...
2021/02/24 13:51:35 [DEBUG] EvalApply: ProviderMeta config value set
2021/02/24 13:51:35 [DEBUG] argocd_cluster.cluster: applying the planned Create change
2021/02/24 13:51:35 [TRACE] GRPCProvider: ApplyResourceChange
2021-02-24T13:51:35.160Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 2021/02/24 13:51:35 [DEBUG] setting computed for "info" from ComputedKeys
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: panic: interface conversion: interface {} is map[string]interface {}, not map[string]string
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: goroutine 110 [running]:
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: github.com/oboukili/terraform-provider-argocd/argocd.expandClusterConfig(0x22004e0, 0xc0006ec3c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/src/github.com/oboukili/terraform-provider-argocd/argocd/structure_cluster.go:41 +0xc8d
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: github.com/oboukili/terraform-provider-argocd/argocd.expandCluster(0xc00062ff10, 0xffffffffffffffff, 0x1, 0x203000)
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/src/github.com/oboukili/terraform-provider-argocd/argocd/structure_cluster.go:32 +0x33e
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: github.com/oboukili/terraform-provider-argocd/argocd.resourceArgoCDClusterCreate(0xc00062ff10, 0x2428980, 0xc000298c40, 0x2, 0x3ad91a0)
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/src/github.com/oboukili/terraform-provider-argocd/argocd/resource_argocd_cluster.go:28 +0x10e
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00036dd40, 0xc0000a9ea0, 0xc000c397c0, 0x2428980, 0xc000298c40, 0x21fd101, 0xc0004b0ef8, 0xc00088c840)
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/resource.go:310 +0x375
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000139b00, 0xc00111fa38, 0xc0000a9ea0, 0xc000c397c0, 0xc000e4c3e8, 0xc000116f28, 0x22004e0)
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/provider.go:294 +0x99
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00074a588, 0x28c2f80, 0xc000386b70, 0xc00062f880, 0xc00074a588, 0xc000386b70, 0xc001117ba0)
2021-02-24T13:51:35.163Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:885 +0x8ab
2021-02-24T13:51:35.164Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x247ffa0, 0xc00074a588, 0x28c2f80, 0xc000386b70, 0xc0001f0960, 0x0, 0x28c2f80, 0xc000386b70, 0xc000cd3c00, 0x30f)
2021-02-24T13:51:35.164Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
2021-02-24T13:51:35.164Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003741c0, 0x28dd220, 0xc000748300, 0xc0000d5500, 0xc0007144e0, 0x3a7aa60, 0x0, 0x0, 0x0)
2021-02-24T13:51:35.164Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
2021-02-24T13:51:35.164Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: google.golang.org/grpc.(*Server).handleStream(0xc0003741c0, 0x28dd220, 0xc000748300, 0xc0000d5500, 0x0)
2021-02-24T13:51:35.164Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xcc5
2021-02-24T13:51:35.164Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000608410, 0xc0003741c0, 0x28dd220, 0xc000748300, 0xc0000d5500)
2021-02-24T13:51:35.164Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa5
2021-02-24T13:51:35.164Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-24T13:51:35.164Z [DEBUG] plugin.terraform-provider-argocd_v1.2.0: 	/home/redacted/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd
2021-02-24T13:51:35.166Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/oboukili/argocd/1.2.0/linux_amd64/terraform-provider-argocd_v1.2.0 pid=9031 error="exit status 2"
2021/02/24 13:51:35 [DEBUG] argocd_cluster.cluster: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Canceled desc = context canceled
```

**Comment by onematchfox** [comment]
Actually figured I might as well do some digging myself. #66 resolves the issue above. Now getting cert errors so need to play around with the `tls_client_config`:

```
Error: something went wrong during cluster resource creation: rpc error: code = Unknown desc = Get "https://....eks.amazonaws.com/version?timeout=32s": x509: certificate signed by unknown authority
```

**Comment by oboukili** [comment]
Many thanks, I merged your PR. Regarding the tls_client_config, yes, you either need to provide the correct ca_data bundle or set insecure to true.

**Comment by onematchfox** [comment]
> Many thanks, I merged your PR. Regarding the tls_client_config, yes, you either need to provide the correct ca_data bundle or set insecure to true.

You're more than welcome. There's another PR incoming. By setting, `tls_client_config.insecure = true` the cluster was registered, but the state failed to save. This has been fixed now and everything seems to work (I'll try and get around to testing the full `tls_client_config` at a later stage.

**Comment by onematchfox** [comment]
Also, one last thing that I did notice when handling the error above, is that the provider fails on refresh if the cluster has been removed from ArgoCD. This means that you need to manually remove the resource from state before re-applying.

```
Error: could not get cluster information: rpc error: code = NotFound desc = cluster "https://.....eks.amazonaws.com" not found
```

**Comment by oboukili** [comment]
Yes this is again a valid point, I will take care of it unless you feel like making another PR before I do start working on it ;) ! Thanks again.

**Comment by oboukili** [comment]
I just added a commit that handles that use case, should you want to test it to confirm the behaviour fixes it.

**Comment by onematchfox** [comment]
> I just added a commit that handles that use case, should you want to test it to confirm the behaviour fixes it.

Just confirming that the latest version solves the refresh issue. Thanks!
