### ISSUE TITLE
Crash when upgrading from 0.4.8 to 1.1.1

### ISSUE THREAD

**Issue by rojopolis** [oboukili/terraform-provider-argocd#59]
My current state has application and project resources created by 0.4.8.  When I upgrade to 1.1.1 the plan fails with `Error: rpc error: code = Unavailable desc = transport is closing` .  I suspect it's crashing on the project and not the applications because the error only seems to happen once.

I'll try to boil this down to a repro case unless the problem is obvious from the stacktrace.

Thanks again for all your work on this provider... it's extremely useful.

Here's the stacktrace (as best I could gather it):
```
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1: 
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1: goroutine 250 [running]:
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1: github.com/oboukili/terraform-provider-argocd/argocd.resourceArgoCDProjectStateUpgradeV0(0xc0010c1410, 0x2ff7e40, 0xc000d25400, 0xc000f52840, 0x2cd1600, 0xc000910890)
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1:   github.com/oboukili/terraform-provider-argocd/argocd/schema_project.go:354 +0x747
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).upgradeJSONState(0xc00000f3f0, 0x0, 0xc0010c1410, 0xc000727b00, 0xc000910890, 0x0, 0x0)
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1:   github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:395 +0xb7
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).UpgradeResourceState(0xc00000f3f0, 0x34b13e0, 0xc0010c0810, 0xc0001197c0, 0xc00000f3f0, 0xc0010c0810, 0xc000e19ba0)
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1:   github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:270 +0x285
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_UpgradeResourceState_Handler(0x306fd60, 0xc00000f3f0, 0x34b13e0, 0xc0010c0810, 0xc000409860, 0x0, 0x34b13e0, 0xc0010c0810, 0xc00109e500, 0x4c7)
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1:   github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3233 +0x214
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00097c380, 0x34cb8e0, 0xc0002c7800, 0xc001590400, 0xc000b547b0, 0x4652920, 0x0, 0x0, 0x0)
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1:   google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1: google.golang.org/grpc.(*Server).handleStream(0xc00097c380, 0x34cb8e0, 0xc0002c7800, 0xc001590400, 0x0)
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1:   google.golang.org/grpc@v1.30.0/server.go:1494 +0xcc5
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000840290, 0xc00097c380, 0x34cb8e0, 0xc0002c7800, 0xc001590400)
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1:   google.golang.org/grpc@v1.30.0/server.go:834 +0xa5
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-29T17:11:56.868-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.1:   google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd```

**Comment by oboukili** [comment]
It is definitely related to #57, the stacktrace you provided is very useful, I will ship a fix soon with proper tests this time.

**Comment by oboukili** [comment]
release v1.1.2 contains the fix, please let me know if that resolves the issue for you, thanks!

**Comment by rojopolis** [comment]
Thanks for the quick fix, but unfortunately it doesn't seem to have resolved the issue.  The symptom is exactly the same, but here's the latest stack trace.  Please let me know if I can help in diagnosing the issue.
```
2021-01-31T22:33:40.822-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2: 
2021-01-31T22:33:40.822-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2: goroutine 244 [running]:
2021-01-31T22:33:40.822-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2: github.com/oboukili/terraform-provider-argocd/argocd.resourceArgoCDProjectStateUpgradeV0(0xc00075ad50, 0x2ff7e40, 0xc000a01e40, 0xc00120e6e0, 0x2cd1600, 0xc00110e130)
2021-01-31T22:33:40.822-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2:   github.com/oboukili/terraform-provider-argocd/argocd/schema_project.go:354 +0x745
2021-01-31T22:33:40.822-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).upgradeJSONState(0xc0001949f8, 0x0, 0xc00075ad50, 0xc0008fd290, 0xc00110e130, 0x0, 0x0)
2021-01-31T22:33:40.822-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2:   github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:395 +0xb7
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).UpgradeResourceState(0xc0001949f8, 0x34b13e0, 0xc00075a150, 0xc001168e80, 0xc0001949f8, 0xc00075a150, 0xc000d82ba0)
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2:   github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:270 +0x285
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_UpgradeResourceState_Handler(0x306fd60, 0xc0001949f8, 0x34b13e0, 0xc00075a150, 0xc000421140, 0x0, 0x34b13e0, 0xc00075a150, 0xc000a4ca00, 0x4c7)
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2:   github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3233 +0x214
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ab180, 0x34cb8e0, 0xc000103080, 0xc0008c8500, 0xc0009014d0, 0x4652920, 0x0, 0x0, 0x0)
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2:   google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2: google.golang.org/grpc.(*Server).handleStream(0xc0002ab180, 0x34cb8e0, 0xc000103080, 0xc0008c8500, 0x0)
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2:   google.golang.org/grpc@v1.30.0/server.go:1494 +0xcc5
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00011c3f0, 0xc0002ab180, 0x34cb8e0, 0xc000103080, 0xc0008c8500)
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2:   google.golang.org/grpc@v1.30.0/server.go:834 +0xa5
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-31T22:33:40.823-0800 [DEBUG] plugin.terraform-provider-argocd_v1.1.2:   google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd
2021-01-31T22:33:40.826-0800 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/oboukili/argocd/1.1.2/darwin_amd64/terraform-provider-argocd_v1.1.2 pid=75836 error="exit status 2"
```

**Comment by oboukili** [comment]
Sorry about that, I'll try and take some time to reproduce it on my end. I should have a fix in a few days at most depending on how busy I am at work. If this is an urgent matter, in the mean time, you could always delete the resource from the state (`terraform state rm argocd_project.myproject`) and reimport it.
Stay tuned.

**Comment by oboukili** [comment]
If you could share your state for that particular argocd_project resource it would also be extremely helpful, thanks!

**Comment by rojopolis** [comment]
Interestingly, if I try to inspect the resource in the state I get this error:
```
tf state show module.us-west-2.module.phoenix\[\"uat\"\].module.argocd.argocd_project.pksd
missing expected [
# module.us-west-2.module.phoenix["uat"].module.argocd.argocd_project.pksd:
resource "argocd_project" "pksd" {
```

Here is the object from the raw state file:
```
{
    "module": "module.us-west-2.module.phoenix[\"uat\"].module.argocd",
    "mode": "managed",
    "type": "argocd_project",
    "name": "pksd",
    "provider": "provider[\"registry.terraform.io/oboukili/argocd\"]",
    "instances": [
      {
        "schema_version": 0,
        "attributes": {
          "id": "pksd-uat",
          "metadata": [
            {
              "annotations": {},
              "generation": 1,
              "labels": {
                "environment": "uat"
              },
              "name": "pksd-uat",
              "namespace": "argo-cd-blue",
              "resource_version": "95472751",
              "uid": "d3d488b3-11e8-4537-a3e8-c43f7ada3327"
            }
          ],
          "spec": [
            {
              "cluster_resource_whitelist": [],
              "description": "Parkside application stack",
              "destination": [
                {
                  "namespace": "*",
                  "server": "https://E35AA7D9F39533CB8FE249DB82F9656B.gr7.us-west-2.eks.amazonaws.com"
                }
              ],
              "namespace_resource_blacklist": [],
              "orphaned_resources": {
                "warn": true
              },
              "role": [],
              "source_repos": [
                "git@github.com:parkside-securities/pksd-live.git"
              ],
              "sync_window": []
            }
          ]
        },
        "sensitive_attributes": [],
        "private": "bnVsbA==",
        "dependencies": [
          "module._global.module.spotinst_account.data.external.account",
          "module._global.module.spotinst_account.null_resource.account",
          "module.us-west-2.aws_iam_user.k8s_qa",
          "module.us-west-2.aws_s3_bucket.kubeconfig",
          "module.us-west-2.data.aws_caller_identity.current",
          "module.us-west-2.data.aws_ec2_transit_gateway.current",
          "module.us-west-2.module.phoenix.aws_iam_access_key.argo_events",
          "module.us-west-2.module.phoenix.aws_iam_user.argo_events",
          "module.us-west-2.module.phoenix.data.aws_availability_zones.current",
          "module.us-west-2.module.phoenix.data.aws_region.current",
          "module.us-west-2.module.phoenix.launchdarkly_environment.this",
          "module.us-west-2.module.phoenix.module.argo.data.aws_region.current",
          "module.us-west-2.module.phoenix.module.argo.random_password.argo",
          "module.us-west-2.module.phoenix.module.cognito.aws_cognito_user_pool.this",
          "module.us-west-2.module.phoenix.module.cognito.aws_cognito_user_pool_client.argo",
          "module.us-west-2.module.phoenix.module.cognito.aws_cognito_user_pool_client.graphql",
          "module.us-west-2.module.phoenix.module.cognito.aws_cognito_user_pool_domain.bdops",
          "module.us-west-2.module.phoenix.module.datomic.module.datomic.data.aws_region.current",
          "module.us-west-2.module.phoenix.module.datomic.module.datomic.random_id.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.data.aws_region.current",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.argocd.module.helm_releases.argocd_application.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.argocd.null_resource.argocd_target_cluster",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_eks_cluster.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_iam_openid_connect_provider.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_iam_role.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_iam_role.workers",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_iam_role_policy.extra_permissions",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_iam_role_policy_attachment.cluster_policy",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_iam_role_policy_attachment.service_policy",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_security_group.cluster",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_security_group.workers",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_security_group_rule.cluster_egress",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_security_group_rule.cluster_ingress",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_security_group_rule.worker_egress",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_security_group_rule.worker_extension_ingress",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_security_group_rule.worker_ingress",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_security_group_rule.worker_self",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.aws_security_group_rule.worker_ssh",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.data.aws_iam_policy_document.workers_assume_role_policy",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.data.tls_certificate.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.eks.module.kubeconfig.aws_s3_bucket_object.kubeconfig",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.kubernetes_resources.null_resource.kubernetes_resource",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.sealed_secrets.tls_private_key.sealed_secrets",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.sealed_secrets.tls_self_signed_cert.sealed_secrets",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.service_account.aws_iam_role.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.service_account.aws_iam_role_policy.s3_bucket_inline",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.service_account.aws_iam_role_policy.sqs_inline",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.service_account.aws_iam_role_policy_attachment.arns",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.service_account.aws_iam_role_policy_attachment.names",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.service_account.data.aws_caller_identity.current",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_instance_profile.workers",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_policy.workers_alb",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_policy.workers_route53",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_role_policy_attachment.workers_AWSAppMeshFullAccess",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_role_policy_attachment.workers_AWSCloudMapFullAccess",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_role_policy_attachment.workers_AmazonElasticFileSystemReadOnlyAccess",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_role_policy_attachment.workers_CloudWatchLogsFullAccess",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_role_policy_attachment.workers_alb",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_iam_role_policy_attachment.workers_route53",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.aws_key_pair.ssh",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.data.aws_region.current",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.random_id.ocean_cluster",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.spotinst_ocean_aws.tf_ocean_cluster",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.spotinst_ocean_aws_launch_spec.tf_ocean_cluster_vng",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.spot.tls_private_key.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_cloudwatch_log_group.flow_log",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_customer_gateway.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_default_network_acl.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_ec2_transit_gateway_vpc_attachment.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_egress_only_internet_gateway.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_eip.nat",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_flow_log.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_iam_policy.vpc_flow_log_cloudwatch",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_iam_role.vpc_flow_log_cloudwatch",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_iam_role_policy_attachment.vpc_flow_log_cloudwatch",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_internet_gateway.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_nat_gateway.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_network_acl.private",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_network_acl.public",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_network_acl_rule.private_inbound",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_network_acl_rule.private_outbound",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_network_acl_rule.public_inbound",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_network_acl_rule.public_outbound",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route.private_ipv6_egress",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route.private_nat_gateway",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route.private_tgw_default",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route.private_tgw_default_ipv6",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route.public_internet_gateway",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route.public_internet_gateway_ipv6",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route.public_tgw_rfc1918_1",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route.public_tgw_rfc1918_2",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route.public_tgw_rfc1918_3",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route_table.private",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route_table.public",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route_table_association.private",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_route_table_association.public",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_subnet.private",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_subnet.public",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint.cloudtrail",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint.dynamodb",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint.efs",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint.events",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint.logs",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint.monitoring",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint.s3",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint.sns",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint.sqs",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint.sts",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint_route_table_association.private_dynamodb",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint_route_table_association.private_s3",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint_route_table_association.public_dynamodb",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_endpoint_route_table_association.public_s3",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpc_ipv4_cidr_block_association.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpn_gateway.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpn_gateway_attachment.this",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpn_gateway_route_propagation.private",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.aws_vpn_gateway_route_propagation.public",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_iam_policy_document.flow_log_cloudwatch_assume_role",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_iam_policy_document.vpc_flow_log_cloudwatch",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_vpc_endpoint_service.cloudtrail",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_vpc_endpoint_service.dynamodb",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_vpc_endpoint_service.efs",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_vpc_endpoint_service.events",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_vpc_endpoint_service.logs",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_vpc_endpoint_service.monitoring",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_vpc_endpoint_service.s3",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_vpc_endpoint_service.sns",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_vpc_endpoint_service.sqs",
          "module.us-west-2.module.phoenix.module.eks.module.eks_green.module.vpc.module.vpc.data.aws_vpc_endpoint_service.sts",
          "module.us-west-2.module.phoenix.module.kafka.confluentcloud_api_key.this",
          "module.us-west-2.module.phoenix.module.kafka.confluentcloud_environment.this",
          "module.us-west-2.module.phoenix.module.kafka.confluentcloud_kafka_cluster.this",
          "module.us-west-2.module.phoenix.module.kafka.kafka_topic.this",
          "module.us-west-2.module.phoenix.module.metabase.random_password.metabase_encryption_key",
          "module.us-west-2.module.phoenix.module.metabase.random_password.metabase_password",
          "module.us-west-2.module.phoenix.module.rds.module.rds.aws_db_subnet_group.this",
          "module.us-west-2.module.phoenix.module.rds.module.rds.aws_rds_cluster.this",
          "module.us-west-2.module.phoenix.module.rds.module.rds.aws_rds_cluster_parameter_group.this",
          "module.us-west-2.module.phoenix.module.rds.module.rds.aws_security_group.this",
          "module.us-west-2.module.phoenix.module.rds.module.rds.random_id.this",
          "module.us-west-2.module.phoenix.module.rds.module.rds.random_password.this",
          "module.us-west-2.module.phoenix.module.rds.module.vpc.aws_subnet.private",
          "module.us-west-2.module.phoenix.module.rds.module.vpc.aws_vpc.this",
          "module.us-west-2.module.phoenix.module.rds.module.vpc.aws_vpc_ipv4_cidr_block_association.this",
          "module.us-west-2.module.phoenix.module.rds.random_password.db",
          "module.us-west-2.module.phoenix.module.route53.aws_acm_certificate.wildcard",
          "module.us-west-2.module.phoenix.module.route53.aws_route53_zone.this",
          "module.us-west-2.module.phoenix.module.s3.aws_s3_bucket.this",
          "module.us-west-2.module.phoenix.module.s3.module.sqs.aws_s3_bucket_notification.this",
          "module.us-west-2.module.phoenix.module.s3.module.sqs.aws_sqs_queue.this"
        ]
      }
    ]
  }
  ```

**Comment by oboukili** [comment]
@rojopolis , thanks for your patience, v1.1.3 should definitely fix this issue hopefully!
