### ISSUE TITLE
Crash when supplying empty sync policy

### ISSUE THREAD

**Issue by Nintorac** [oboukili/terraform-provider-argocd#94]
I have an application with the following sync policy

```terraform
    sync_policy {
      automated = {}
    }
```

and terraform crashes with the following
```
goroutine 151 [running]:
github.com/oboukili/terraform-provider-argocd/argocd.expandApplicationSyncPolicy(0xc000f42040, 0x1, 0x1, 0xb, 0xc000efae28, 0x1)
        github.com/oboukili/terraform-provider-argocd/argocd/structure_application.go:263 +0xc13
github.com/oboukili/terraform-provider-argocd/argocd.expandApplicationSpec(0xc00078bf80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/oboukili/terraform-provider-argocd/argocd/structure_application.go:43 +0x2ea
github.com/oboukili/terraform-provider-argocd/argocd.expandApplication(0xc00078bf80, 0xc000c98e70, 0xd, 0x0, 0x0, 0xc000c98e80, 0x5, 0x0, 0x0, 0x0, ...)
        github.com/oboukili/terraform-provider-argocd/argocd/structure_application.go:19 +0x106
github.com/oboukili/terraform-provider-argocd/argocd.resourceArgoCDApplicationCreate(0xc00078bf80, 0x24304a0, 0xc00062ac00, 0x2, 0x3ac8e80)
        github.com/oboukili/terraform-provider-argocd/argocd/resource_argocd_application.go:44 +0xc5
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000751830, 0xc000e96140, 0xc000cfb8c0, 0x24304a0, 0xc00062ac00, 0x2205501, 0xc000e907f8, 0xc000ee88d0)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/resource.go:310 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000d80280, 0xc000777a38, 0xc000e96140, 0xc000cfb8c0, 0xc000edb168, 0xc000309f28, 0x2208920)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00061c5c8, 0x28ca9e0, 0xc000e7d650, 0xc00078b7a0, 0xc00061c5c8, 0xc000e7d650, 0xc000981ba0)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:885 +0x8ab
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x2487ac0, 0xc00061c5c8, 0x28ca9e0, 0xc000e7d650, 0xc000e880c0, 0x0, 0x28ca9e0, 0xc000e7d650, 0xc00071a480, 0x47d)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c2fc0, 0x28e4ce0, 0xc000803980, 0xc00012ea00, 0xc000ac8570, 0x3a6a7a0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0001c2fc0, 0x28e4ce0, 0xc000803980, 0xc00012ea00, 0x0)
        google.golang.org/grpc@v1.30.0/server.go:1494 +0xcc5
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000b80300, 0xc0001c2fc0, 0x28e4ce0, 0xc000803980, 0xc00012ea00)
        google.golang.org/grpc@v1.30.0/server.go:834 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd

Error: The terraform-provider-argocd_v1.2.2 plugin crashed!
```

**Comment by MrLuje** [comment]
fixed in 2.2.8
